spring:
  application:
    name: gateway-server
  config:
    import: configserver:http://localhost:8888
  cloud:
    gateway:
      # discovery.locator:
      #   enabled: true
      #   lowerCaseServiceId: true
      routes:
        - id: todo-service
          uri: lb://eureka-client-todo-service
          predicates:
            - Path=/todos/**
          filters:
            - RewritePath=/todos/(?<path>.*), /$\{path}
        - id: todo-consumer
          uri: lb://eureka-client-todo-consumer
          predicates:
            - Path=/consumer/**
          filters:
            - RewritePath=/consumer/(?<path>.*), /$\{path}

server:
  port: 8073

eureka:
  instance:
    preferIpAddress: true

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info, health, httptrace, configprops, beans, auditevents, gateway, refresh

  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    configprops:
      enabled: true
    beans:
      enabled: true
    httptrace:
      enabled: true
    auditevents:
      enabled: true
    gateway:
      enabled: true
    refresh:
      enabled: true
  trace:
    http:
      enabled: true


  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

