eureka:
  client:
# https://docs.spring.io/spring-cloud-netflix/docs/current/reference/html/#spring-cloud-eureka-server-standalone-mode
# Standalone Mode
#    registerWithEureka: false
#    fetchRegistry: false
    service-url:
      defaultZone: http://${other.eureka.host}:${other.eureka.port}/eureka
  server:
    enable-self-preservation: false

---
spring:
  config:
    activate:
      on-profile: eureka-1
  application:
    name: eureka-1

server:
  port: 8761

eureka:
  instance:
    hostname: cloud1.local

other:
  eureka:
    host: cloud2.local
    port: 8762

---
spring:
  config:
    activate:
      on-profile: eureka-2
  application:
      name: eureka-2

server:
  port: 8762

eureka:
  instance:
    hostname: cloud2.local

other:
  eureka:
    host: cloud1.local
    port: 8761
---
spring:
  config:
    activate:
      on-profile: docker-eureka-1
  application:
    name: eureka-1

server:
  port: 8761

eureka:
  instance:
    hostname: eureka-1

other:
  eureka:
    host: eureka-2
    port: 8762

---
spring:
  config:
    activate:
      on-profile: docker-eureka-2
  application:
      name: eureka-2

server:
  port: 8762

eureka:
  instance:
    hostname: eureka-2

other:
  eureka:
    host: eureka-1
    port: 8761
