services:
  eureka-client-consumer:
    image: eureka-client-consumer:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    depends_on:
      eureka-1:
        condition: service_started
      eureka-2:
        condition: service_started
      gateway-server:
        condition: service_started
      config-server:
        condition: service_started

  gateway-server:
    image: gateway-server:0.0.1-SNAPSHOT
    ports:
      - "8073:8073"
    depends_on:
      eureka-1:
        condition: service_started
      eureka-2:
        condition: service_started
      config-server:
        condition: service_started

  eureka-client:
    image: eureka-client:0.0.1-SNAPSHOT
    #    ports:
    #  - "8888:8888"
    depends_on:
      eureka-1:
        condition: service_started
      eureka-2:
        condition: service_started
      config-server:
        condition: service_started

  eureka-1:
    image: service-registry:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker-eureka-1

  eureka-2:
    image: service-registry:0.0.1-SNAPSHOT
    ports:
      - "8762:8762"
    environment:
      SPRING_PROFILES_ACTIVE: docker-eureka-2

  config-server:
    image: config-server:0.0.1-SNAPSHOT
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      gogs:
        condition: service_started

  gogs:
    image: gogs/gogs:latest
    ports:
      - "10880:3000"
    volumes:
      - ${PWD}/config-server/gogs:/data
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
        #      - ${PWD}/config-server/all-databases.sql:/docker-entrypoint-initdb.d/start.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "database"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
