#server:
#  port: 0
eureka:
  client:
    service-url:
      defaultZone: 
      # http://eureka1:8761/eureka/
          http://cloud1.local:8761/eureka,
          http://cloud2.local:8762/eureka

todo:
  list:
    length: 9

# it is recommended to set the key as an OS environmental variable and reference the variable in your file. This is for more security
encrypt:
  key: secretkey
