spring:
  cloud:
    gateway:
      routes:
        - id: todo-service-alias
          uri: lb://eureka-client-todo-service
          predicates:
            - Path=/tds/**
          filters:
            - RewritePath=/tds/(?<path>.*), /$\{path}
        - id: todo-service
          uri: lb://eureka-client-todo-service
          predicates:
            - Path=/todos/**
          filters:
            - RewritePath=/todos/(?<path>.*), /$\{path}
        - id: todo-consumer
          uri: lb://eureka-client-todo-consumer
          predicates:
            - Path=/consumer/**
          filters:
            - RewritePath=/consumer/(?<path>.*), /$\{path}

