spring:
  application:
    name: eureka-client-todo-consumer
  config:
    import: configserver:http://localhost:8888
# server:
#   port: 8081
eureka:
  # client:
  #   serviceUrl:
  #     defaultZone: 
  #       http://localhost:8761/eureka,
  #       http://localhost:8762/eureka
        # ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true


management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info, health, httptrace, configprops, beans, auditevents, refresh

  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    configprops:
      enabled: true
    beans:
      enabled: true
    httptrace:
      enabled: true
    auditevents:
      enabled: true
    refresh:
      enabled: true
  trace:
    http:
      enabled: true

  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

resilience4j.circuitbreaker:
  instances:
    getTodoWithId:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException

# to understand the bulkhead concept, watch https://www.youtube.com/watch?v=Kh3HxWk8YF4
resilience4j.bulkhead:
  instances:
    getTodoWithIdBulkhead:
      maxWaitDuration: 10ms
      maxConcurrentCalls: 10

resilience4j.thread-pool-bulkhead:
  instances:
    getTodoWithIdBulkhead:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1
      keepAliveDuration: 20ms

resilience4j.retry:
  instances:
    retryTodoService:
      maxAttempts: 5
      waitDuration: 1000
      retry-exceptions:
        - java.util.concurrent.TimeoutException

resilience4j.ratelimiter:
  instances:
    ratelimiterTodoService:
      timeoutDuration: 1000ms
      limitRefreshPeriod: 5000
      limitForPeriod: 5



