spring:
  application:
    name: eureka-client-todo-consumer
  config:
    import: configserver:http://config-server:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8089/realms/spmia-realm
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8089/realms/spmia-realm
            user-name-attribute: preferred_username
        registration:
          keycloak:
            scope: openid
            authorization-grant-type: password
            client-id: consumer
            client-secret: sILBWvz2VS0Ivc6fgnHgktVVAyaN1h6o
# server:
#   port: 8081
eureka:
  # client:
  #   serviceUrl:
  #     defaultZone: 
  #       http://localhost:8761/eureka,
  #       http://localhost:8762/eureka
        # ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true


management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info, health, httptrace, configprops, beans, auditevents, refresh

  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    configprops:
      enabled: true
    beans:
      enabled: true
    httptrace:
      enabled: true
    auditevents:
      enabled: true
    refresh:
      enabled: true
  trace:
    http:
      enabled: true

  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

resilience4j.circuitbreaker:
  instances:
    getTodoWithId:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException

# to understand the bulkhead concept, watch https://www.youtube.com/watch?v=Kh3HxWk8YF4
resilience4j.bulkhead:
  instances:
    getTodoWithIdBulkhead:
      maxWaitDuration: 10ms
      maxConcurrentCalls: 10

resilience4j.thread-pool-bulkhead:
  instances:
    getTodoWithIdBulkhead:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1
      keepAliveDuration: 20ms

resilience4j.retry:
  instances:
    retryTodoService:
      maxAttempts: 5
      waitDuration: 1000
      retry-exceptions:
        - java.util.concurrent.TimeoutException

resilience4j.ratelimiter:
  instances:
    ratelimiterTodoService:
      timeoutDuration: 1000ms
      limitRefreshPeriod: 5000
      limitForPeriod: 5

cc:
  asako:
    url: '{cipher}7fc127543d017234b3e56cfe7ef0aeded3e9a8f8edea99098441d6bcbfcce630' #asako.cc

logging:
  config: classpath:logback-spring.xml
  # level:
  #   org:
  #     springframework:
  #       security: DEBUG

