spring:
  application:
    name: eureka-client-todo-consumer
  config:
    import: configserver:http://localhost:8888
# server:
#   port: 8081
eureka:
  # client:
  #   serviceUrl:
  #     defaultZone: 
  #       http://localhost:8761/eureka,
  #       http://localhost:8762/eureka
        # ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true


management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info, health, httptrace, configprops, beans, auditevents, refresh

  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    configprops:
      enabled: true
    beans:
      enabled: true
    httptrace:
      enabled: true
    auditevents:
      enabled: true
    refresh:
      enabled: true
  trace:
    http:
      enabled: true

  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true




