spring:
  application: 
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: http://localhost:10880/gogs/todo-config
        #   username: tacocloud
        #   password: s3cr3tP455w0rd
          default-label: master

server:
  port: 8888
#   servlet:
#     context-path: /config-server

# it is recommended to set the key as an OS environmental variable and reference the variable in your file. This is for more security
encrypt:
  key: secretkey

logging:
  file:
    name: "logs/config-server-info.log"

management:
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    config:
      server:
        git:
          uri: http://gogs:3000/gogs/todo-config
